spring.application.name=legaltech

server.port=8080

# SQL Server
spring.datasource.url=jdbc:sqlserver://LAPTOP-K35VD8M9:1433;databaseName=LegalTechDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=legaltech
spring.datasource.password=LegalTech@2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG